In [1]:
from Advn import *

In [2]:
acao = Advfn('XPLG11')

In [4]:
prices = acao.getPrices('01/01/09', '27/03/20')
prices

,Data,Fechamento,Variação,Variação (%),Abertura,Máxima,Mínima,Volume
0,27 Mar 2020,"101,78","-0,87","-0,85%","102,65","103,95","100,06",84.252
1,26 Mar 2020,"102,65","1,85","1,84%","100,50","103,96","98,30",65.273
2,25 Mar 2020,"100,80","8,01","8,63%","94,20","101,20","94,20",79.840
3,24 Mar 2020,"92,79","5,34","6,11%","92,00","95,62","90,18",38.150
4,23 Mar 2020,"87,45","-5,41","-5,83%","93,00","93,00","85,01",48.865
...,...,...,...,...,...,...,...,...
480,14 Jun 2018,"96,53","-1,46","-1,49%","97,51","97,99","96,50",2.780
481,13 Jun 2018,"97,99","0,19","0,19%","97,97","98,00","97,00",1.559
482,12 Jun 2018,"97,80","1,30","1,35%","98,49","99,50","97,00",3.163
483,11 Jun 2018,"96,50","-1,45","-1,48%","99,39","99,50","96,50",4.751
484,08 Jun 2018,"97,95","5,62","6,09%","92,53","99,49","92,53",2.790

In [5]:
yields = acao.getYields()
yields

      Data-Com   Pagamento Valor Mês de Referência Dividend Yield
0   30/12/2019  15/01/2020  0,64           12-2019          0,42%
1   29/11/2019  13/12/2019  0,64           11-2019          0,51%
2   31/10/2019  14/11/2019  0,64           10-2019          0,57%
3   30/09/2019  14/10/2019  0,06           09-2019          0,06%
4   30/09/2019  14/10/2019  0,61           09-2019          0,57%
5   30/08/2019  13/09/2019  0,61           08-2019          0,57%
6   31/07/2019  14/08/2019  0,61           07-2019          0,57%
7   28/06/2019  12/07/2019  0,61           06-2019           0,6%
8   31/05/2019  14/06/2019  0,27             05-19          0,26%
9   31/05/2019  14/06/2019  0,61             05-19          0,59%
10  30/04/2019  15/05/2019  0,68             04-19          0,67%
11  29/03/2019  12/04/2019  0,68             03-19          0,68%
12  28/02/2019  18/03/2019  0,67             02-19          0,65%
13  31/01/2019  14/02/2019  0,67             01-19          0,66%
14  28/12/2018  15/01/2019  0,65             12-18          0,65%
15  30/11/2018  14/12/2018  0,65             11-18          0,67%
16  31/10/2018  16/11/2018  0,60             10-18          0,64%
17  28/09/2018  15/10/2018  0,70             09-18           0,8%
18  31/08/2018  17/09/2018  0,50             08-18          0,57%
19  31/07/2018  14/08/2018  0,13             07-18          0,14%
20  29/06/2018  13/07/2018  0,32             06-18          0,33%